layout_spectrum: 0.421147
color:
  saturation: 0.06810036
  brandStrength: 0.3333333
  lightness: 1
  brandColors:
    - '#DED8F1'
    - '#4B536F'
    - '#7687A4'
    - '#4BB4E1'
    - '#C69AAC'
  rhythmicContrast: 0.2150538
typography_spectrum: 0.3673835
name: MediatedReality
