name: MediatedReality
favicon: null
layout_spectrum: 0.421147
typography_spectrum: 0.3673835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8dad9'
    - '#140801'
    - '#888f9a'
    - '#4c5255'
    - '#9c5a3e'
  brandStrength: 0.3333333
  lightness: 1
  saturation: 0.06810036
  rhythmicContrast: 0.2150538
purpose: []
